region: us
version: '2'
authtoken: 2kOGI95FBzg1tU0KOE8r3LCoDTd_aLV3HpVL6CMwwU3BtU3F
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http